### ISSUE TITLE
TreeView is not working on IE11.

### ISSUE THREAD

**Issue by Hyung-Kim** [excubo-ag/Blazor.TreeViews#11]
I'm developing on IE11 using the Blazor server side. But, this package is not working on IE11. Is it right?

**Comment by stefanloerwald** [comment]
Hi @Hyung-Kim,

I cannot recommend using IE11 at all with Blazor. It is only supported with .NET 3.1 and Blazor server-side, and it is not supported with .NET 5 or later.

I just had a quick look at this and it seems that both CSS is broken for IE11 and events are also not propagated to the server. Given that this library doesn't do anything overly complex in terms of events and they're not working, I'm not inclined to fix this for a defacto abandoned browser.

If this is a critical issue to you, I can only recommend forking the repo and modifying it for this explicit purpose.

BR
Stefan

**Comment by Hyung-Kim** [comment]
@stefanloerwald  Ok I modified CSS code. so It is working well. Thank you.
