### ISSUE TITLE
how to set initial value of checkbox?

### ISSUE THREAD

**Issue by Hyung-Kim** [excubo-ag/Blazor.TreeViews#12]
I want to change checkbox value. But, I don't know what to do.

**Comment by stefanloerwald** [comment]
Have a look at the demo pages: the [filter example](https://excubo-ag.github.io/Blazor.TreeViews/filter) shows that you can easily set the initial selection by setting the `SelectedItems` parameter. The code is [available here](https://github.com/excubo-ag/Blazor.TreeViews/blob/main/TestProject_Components/Pages/FilterBy.razor).

**Comment by Hyung-Kim** [comment]
@stefanloerwald 
The selectedValue is not working, when parent is not selected.
Please check this situation.
Example.   
Items =  new List<string>(1, 1.2, 1.3)
GetParent =       ex) 1.3 => 1,   1.2 => 1,
SelectedValue = 1.3

**Comment by Hyung-Kim** [comment]
![20201209_151025](https://user-images.githubusercontent.com/23274971/101591943-c8678200-3a30-11eb-8dd5-c27c16572af2.png)
above code is part of filter example, but it is not working because of GetParent() method

**Comment by stefanloerwald** [comment]
This is indeed a bug. It's fixed in version 1.4.0.

In the future, please do not post screenshots of code. Post the code as text instead. Thanks
