### ISSUE TITLE
Customized Checkbox Error

### ISSUE THREAD

**Issue by HongJinHyeon** [excubo-ag/Blazor.TreeViews#13]
Hi there!
I'm using Treeview with Customized Checkbox
there is no errors on the code but runtime it goes error

my code is

exactly same  CustomizedCheckbox_MatBlazor.razor 
 

the error message is blow

Microsoft.JSInterop.JSException: Could not find 'matBlazor.matCheckbox.init' ('matBlazor' was undefined).
Error: Could not find 'matBlazor.matCheckbox.init' ('matBlazor' was undefined).
    at https://localhost:44363/_framework/blazor.server.js:1:67388
    at Array.forEach (<anonymous>)
    at e.findFunction (https://localhost:44363/_framework/blazor.server.js:1:67348)
    at b (https://localhost:44363/_framework/blazor.server.js:1:69090)
    at https://localhost:44363/_framework/blazor.server.js:1:70036
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:44363/_framework/blazor.server.js:1:70009)
    at https://localhost:44363/_framework/blazor.server.js:1:26293
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:44363/_framework/blazor.server.js:1:26263)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at MatBlazor.BaseMatComponent.JsInvokeAsync[T](String code, Object[] args)
   at MatBlazor.BaseMatCheckboxInternal`1.<.ctor>b__4_0()
   at MatBlazor.BaseMatComponent.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

where am I wrong ;(

**Comment by stefanloerwald** [comment]
Hi @HongJinHyeon 

Seems like you're not including the appropriate javascript. See https://www.matblazor.com/ for documentation of MatBlazor.

**Comment by HongJinHyeon** [comment]
Thanks bro!!
I've just fixed that error ^.^

I have another question

1.Is it possible add Icon to TreenodeItem just after check box. also change the icon image depending on it's expand states ?
2.There a any way change Node Arrow Icon ( > ^)
3.Can I adjust  the intent of TreeNode between parent and child?
 ( It's too narrow..:()

thanks in advance..

**Comment by stefanloerwald** [comment]
> 1.Is it possible add Icon to TreenodeItem just after check box. also change the icon image depending on it's expand states ?

Yes, this is possible, see https://excubo-ag.github.io/Blazor.TreeViews/item_template

> 2.There a any way change Node Arrow Icon ( > ^)

No, this is currently not possible, but it's feasible. Please open a new issue for this and describe how you would like to customize it (e.g. it is relevant if you need more information to render the icon than just the information whether it is collapsed/expanded and whether it has children or not).

> 3.Can I adjust the intent of TreeNode between parent and child?
> ( It's too narrow..:()

This is not possible with v1.4.0, but as it's clearly something that's required in some situations, I'll add that shortly.

**Comment by stefanloerwald** [comment]
> > 3.Can I adjust the intent of TreeNode between parent and child?
> > ( It's too narrow..:()
> 
> This is not possible with v1.4.0, but as it's clearly something that's required in some situations, I'll add that shortly.

As of v1.5.0, this is now possible and the [item template demo](https://excubo-ag.github.io/Blazor.TreeViews/item_template) shows how it can be used.

**Comment by HongJinHyeon** [comment]
really really thanks
this treeview is reeeeeally helping me!!!
