### ISSUE TITLE
Manage selected items through code for poco class type based checkbox list

### ISSUE THREAD

**Issue by paulc1983** [excubo-ag/Blazor.TreeViews#15]
Hi 

I have a poco class and I cant work out how to set the initial selection (or change the selection programmatically)

My class is:
```cs
 public class SupplierPlanListItem
    {
        public int Id { get; set; }

        public int? ParentId { get; set; }

        public string SupplierName { get; set; }

        public int? Duration { get; set; }

        public string Product { get; set; }

        /// <summary>
        /// should it be selected by default
        /// </summary>
        public bool Selected { get; set; } = false;
    }
```

and my markup looks like 

```xml
<TreeView @ref="treeViewRef" Items="SupplierTreeNodesNormalized" GetParent="GetSupplierParent" AllowSelection="true" @bind-SelectedItems="SelectedPlans" T="SupplierPlanListItem" ItemClass="SupplierPlanListItem">
    <ItemTemplate>
        <div class="@($"{context.Item.Type}-treeview-item")">
            <label class="form-check-label">@getDisplayText(context.Item)</label>
        </div>        
    </ItemTemplate>
</TreeView>
```

I have tried setting the selected plans using linq, clearing it and adding a range and setting it through the reference. Nothing seems to work. What am I doing wrong?

Thanks

Also, it would be nice to be able to set row level css classes or have dividers in the list.

Thanks

Paul

**Comment by stefanloerwald** [comment]
Hi Paul,

you are not showing how you define `SelectedPlans`. Can you please add that?

Regarding your second question about row css: You are free to fully customize this as shown in the [demo](https://excubo-ag.github.io/Blazor.TreeViews/item_template), code is available [here](https://github.com/excubo-ag/Blazor.TreeViews/blob/main/TestProject_Components/Pages/CustomItemTemplate.razor)

Stefan

**Comment by paulc1983** [comment]
Hi 

Thanks for getting back to me. 

I have made a blazor fiddle (that doesnt run without the nuget package for the treeview). hopfully this shows what im experimenting with. Apologies for how messy it is!

https://blazorfiddle.com/s/1e3oqpct


I have tried pretty much all the ways i can think of. Below is my on parameters set method in its current state. 

```cs
protected override async Task OnParametersSetAsync()
{
    await base.OnParametersSetAsync();
    //SelectedPlans.Clear();
    //SelectedPlans.Add(gp36);
    //SelectedPlans.AddRange(SupplierTreeNodesNormalized.Where(x => x.Selected)); //.ToList();


    var supplierIds = SupplierTreeNodesNormalized.Where(x => x.ParentId != null).Select(x => x.ParentId).Distinct();
    var selectedSuppliers = SupplierTreeNodesNormalized.Where(x => x.Type == ItemType.Supplier && supplierIds.Contains(x.Id));

    SelectedPlans = SupplierTreeNodesNormalized.Where(x => x.Selected).ToList();
    //treeViewRef.SelectedItems = SelectedPlans;
    StateHasChanged();
}
```

the selected plans list does contain the items i expect but the UI is not updated. Its worth mentioning this is using blazor server side, not WASM

Thanks

Paul

**Comment by stefanloerwald** [comment]
Hi Paul,

thanks for the code. I can reproduce the issue. While I were able to modify the code base to make this possible, it requires a series of fundamental changes that I believe are detrimental to the library itself. Since the items you have contain the knowledge about whether the item is selected or not, this is my recommended approach for you:

- remove `AllowSelection="true" @bind-SelectedItems="SelectedPlans"` from your tree view
- adjust the `ItemTemplate` to include a checkbox that you bind to the `Selected` property or your item (should be `context.Item.Selected`)

BR
Stefan

**Comment by paulc1983** [comment]
Hi

Thanks again. The selected property was there just so i could test how I can drive the component from the code before deciding on what data and ui solution to go with, but what you said makes sense as I want to customize the look and feel anyway and had tunnel vision on the existing checkbox examples in the demo project.

Thanks for responding so quickly and writing a nice component

Paul

**Comment by paulc1983** [comment]
As a side observation. when using the templates without allow selection it appears it only works with getChildern and not getParent. Im not sure if this is by design so thought i would point it out just in case its not.

Thanks 

Paul

**Comment by stefanloerwald** [comment]
Hi Paul,

I'm not sure what you mean by "templates". Do you mind opening a new issue and describing it in a bit more detail?

Thanks
Stefan
