### ISSUE TITLE
Open just by clicking on arrow

### ISSUE THREAD

**Issue by Kruki** [excubo-ag/Blazor.TreeViews#17]
It would be great, if there would be an option that prevents opening the subtree when clicking on the ItemTemplate.

**Comment by stefanloerwald** [comment]
Hi @Kruki,

this is easy to achieve by adding `@onclick:stopPropagation` to your `ItemTemplate`. You may also want to adjust the `cursor`-style.

Example:
```
<TreeView Items="Nested" GetChildren="(item) => item.Children">
    <ItemTemplate>
        <span @onclick:stopPropagation>@context.Item.Self</span>
    </ItemTemplate>
</TreeView>
```

BR
Stefan

**Comment by Kruki** [comment]
Hey Stefan,
Thanks a lot, it works!

Great library, I hope more people like you start doing MIT-Licensed libraries for blazor!

Best Regards
Tobias
