### ISSUE TITLE
NuGet project URL is wrong

### ISSUE THREAD

**Issue by celalergun** [excubo-ag/Blazor.TreeViews#18]
I noticed that there is an upgrade for the NuGet package and clicked on the link to check to see the change log. Got a 404.

**Comment by stefanloerwald** [comment]
Hi @celalergun,

I've just tried the links in the readme and all seem fine to me. I wonder which link you are referring to? 

Stefan

**Comment by celalergun** [comment]
The one in the NuGet package manager. It says "project url". If I click on the link I get a 404.

**Comment by stefanloerwald** [comment]
Ah, that's the package metadata. Now I see it. Thanks for reporting. I'll fix right away.

**Comment by stefanloerwald** [comment]
Fixed by 55f1b0a1e89733ff0e0a49f6de744d025e6b357e

Thanks for reporting!
