### ISSUE TITLE
FilterBy with TreeViewAsync - Example

### ISSUE THREAD

**Issue by Joni-Torrado** [excubo-ag/Blazor.TreeViews#19]
Hi,

Can you create an example of TreeViewAsync with filtering using FilterBy attribute?
I'm struggling on this!

Thanks.

**Comment by stefanloerwald** [comment]
Hi @Joni-Torrado,

it works the same way the synchronous tree view does it. Here's a demo page: https://excubo-ag.github.io/Blazor.TreeViews/filtered_asynchronous_tree_view The difference to the normal async tree view page is that the item C1 is filtered.

Stefan

**Comment by Joni-Torrado** [comment]
Hi @stefanloerwald,

Thanks for the example..
But I need an example when having a input text on the page to filter the treeview based on the value text.
Can you do that?

**Comment by stefanloerwald** [comment]
Sorry, but that's out of scope for this project.
