### ISSUE TITLE
support single node selection

### ISSUE THREAD

**Issue by qinhuaihe** [excubo-ag/Blazor.TreeViews#20]
Can this component support single selection mode like below img?
![image](https://user-images.githubusercontent.com/18019463/115689487-b5759e80-a38e-11eb-9542-2cc6e741731b.png)

**Comment by stefanloerwald** [comment]
Hi @qinhuaihe,

this can be achieved, but it's not a built-in feature. This is how I would do it:

- Create a tree view, without any selection parameters
- Modify the item template to include a callback that handles the selection of an item
- Modify the item template to apply the style for when the item is selected

Hope that helps
Stefan

**Comment by qinhuaihe** [comment]
thank you for your enlightenment.
