### ISSUE TITLE
initial selected broken

### ISSUE THREAD

**Issue by qinhuaihe** [excubo-ag/Blazor.TreeViews#23]
I found my code made the initial selected broken . Initially setting `3.1.1` selected makes the whole `3` branch selected. I'm wondering how to fix it now.
![image](https://user-images.githubusercontent.com/18019463/118087468-30632f80-b3f8-11eb-9661-9547f98fe5c6.png)

**Comment by stefanloerwald** [comment]
Fascinating! Yes, this is broken. I'll investigate.
