### ISSUE TITLE
Clarification Question on HasChildrenAsync

### ISSUE THREAD

**Issue by christophwille** [excubo-ag/Blazor.TreeViews#30]
Sample in question https://github.com/excubo-ag/Blazor.TreeViews/blob/main/TestProject_Components/Pages/AsynchronousTreeView.razor

I have a use case where I only know after calling GetChildrenAsync on an item whether is has children or not (think directory that can be empty or not). And that call itself is expensive, so I cannot reuse it for HasChildrenAsync. Can I get away with not implementing HasChildrenAsync? Also, after the initial call to GetChildrenAsync which might return no children at all - is there a way to tell the control "oh, although the children are null, don't ever try to call me again because I know there are no children"?

**Comment by stefanloerwald** [comment]
Hi @christophwille,

I'm not 100% sure whether I have fully understood the use case, but I think you can use of how `Task<T>` works.

```cs
var task= SomeMethodAsync();
var result = await task;
var resultAgain = await task; // will yield the same result as the line before!
```

You can "await" the same task as often as you wish. All except the first time will return immediately, returning the result that you got the first time.

So now you can do something like (just as an example, you may want to do it entirely differently) storing the tasks in a dictionary (`Dictionary<Child, Task<bool>>`), indexed by the child you're processing. If the child was already processed, there is an item in the dictionary, so just await the task for this child. Otherwise, add an item to that dictionary and await the task you just put into the dictionary.

This will make sure you only ever execute that task once per child.

Does that help?

BR
Stefan

**Comment by christophwille** [comment]
I'll expand on my use case - here is how the simplified structure looks like when fully expanded:

```
\dir1
  \subdir1
  \subdir2
     file1
     file2
\dir2
  \subdir3
     file4
     \subdir4
     \subdir5
        file5
```

A call to a fictional gRPC endpoint getDirectoryContents(dir2) would yield the subdirectories and files in that directory. For the subdirectories, I don't know if there is anything in there, and I can find out only by enumerating (which is expensive - and why I don't want to do it).

Because it is expensive, I also don't want to enumerate again. So for the subdir4 case, it is empty. After calling getDirectoryContents(subdir4), I shouldn't be called again.

In a way I want do dynamically expand the tree, but once a node has been expanded once, I want to keep the results around - even if the node turns out to have no leaf nodes at all and it itself is the terminal leaf node in that branch. Somehow a mix of not using HasChildren but blindly calling GetChildren and then remembering if there were any to avoid future calls.

**Comment by stefanloerwald** [comment]
I think the approach I outlined will work nicely for this. You probably want to create a `Dictionary<Directory, Task<List<Entry>>>`. For `HasChildrenAsync`, you await that task and return `result.Any()`, and for `GetChildrenAsync`, you return the result itself.

**Comment by christophwille** [comment]
Keeping Tasks around... how about this idea: I tack a `bool? HasChildren` property onto the Item. In HasChildren, I return true for !HasValue and true. Once GetChildren returns, I modify the HasChildren property (if null) of the Item.

Would the control pick up on those property changes?

In that scenario: is the control "smart enough" to know that is has the children data already (the sample reloads; is that the default or is there a way to "cache" and keep the data around?)

**Comment by stefanloerwald** [comment]
If you don't want to keep tasks around, you don't have to, but there's no harm in doing so whatsoever. What you want to achieve is storing the information whether you ran the query already and what its result was. Whether you do that with a boolean or by simply keeping the task is up to you.

**Comment by christophwille** [comment]
So maybe the best idea is to have a "shadow tree" (data structure) to the side that I use to store the real data and sync that via the events to/from the treeview.

**Comment by stefanloerwald** [comment]
I would still say the task cache is the best idea, but I can't force you into using it. Here's the demo page slightly modified to use exactly that caching mechanism:

(Compare that to https://github.com/excubo-ag/Blazor.TreeViews/blob/main/TestProject_Components/Pages/AsynchronousTreeView.razor)

```html
@page "/asynchronous_tree_view"
<SourceCodeLink Repository="Blazor.TreeViews" Page="@nameof(AsynchronousTreeView)" />

<h4>Default loading template</h4>
<TreeViewAsync GetChildrenAsync="GetChildrenAsync" HasChildrenAsync="HasChildrenAsync" AllowSelection="true" SelectedItems="SelectedItems">
    <ItemTemplate>
        @context.Item.Self
    </ItemTemplate>
</TreeViewAsync>

<h4>Custom loading template</h4>
<TreeViewAsync GetChildrenAsync="GetChildrenAsync" HasChildrenAsync="HasChildrenAsync" AllowSelection="true" SelectedItems="SelectedItems">
    <ItemTemplate>
        @context.Item.Self
    </ItemTemplate>
    <LoadingTemplate>
        Loading...
    </LoadingTemplate>
</TreeViewAsync>

@code {
    private Dictionary<Item, Task<List<Item>>> cache = new();
    private List<Item> SelectedItems { get; set; }

    private static async Task<List<Item>> GetChildrenAsyncImpl(Item i)
    {
        await Task.Delay(2000);
        return i.Self switch
        {
            "A" => new List<Item> { new Item { Self = "B1" }, new Item { Self = "B2" } },
            "B1" => new List<Item> { new Item { Self = "C1" }, new Item { Self = "C2" } },
            "B2" => new List<Item> { new Item { Self = "C1" } },
            "C1" => new List<Item> { new Item { Self = "D1" } },
            _ => new List<Item>()
        };
    }

    private async Task<List<Item>> GetChildrenAsync(Item i)
    {
        if (i == null)
        {
            return new List<Item> { new Item { Self = "A" }, new Item { Self = "A" } };
        }
        if (!cache.ContainsKey(i))
        {
            cache.Add(i, GetChildrenAsyncImpl(i));
        }
        return await cache[i];
    }

    private async Task<bool> HasChildrenAsync(Item i)
    {
        var results = await GetChildrenAsync(i);
        return results != null && results.Any();
    }

    private class Item
    {
        public string Self { get; set; }
    }
}
```
