### ISSUE TITLE
Resetting TreeViewAsync

### ISSUE THREAD

**Issue by christophwille** [excubo-ag/Blazor.TreeViews#31]
Scenario: I have a dropdown to select base source for treeview. On change of item in dropdown, remove all existing items in treeview, and start GetChildrenAsync anew from that new root.

I will admit that I didn't find a property / method that would allow me to do that.

**Comment by stefanloerwald** [comment]
Sounds like you want to add `@key="Items"` onto the TreeView component, where `Items` is the collection of items to be displayed in the tree view. If you then assign a new value to `Items`, the entire tree view is recreated, resetting it as you want.

**Comment by christophwille** [comment]
ok, I would have never guessed that this property would do my bidding esp. given its IntelliSense.

**Comment by stefanloerwald** [comment]
It's not a property of this library, but of blazor in general. Glad it solved your issue.
