### ISSUE TITLE
Struct for GetParent

### ISSUE THREAD

**Issue by Chadley08** [excubo-ag/Blazor.TreeViews#33]
TreeView.razor in the GetParent case checks GetParent for a null value as below:

```
@if (GetParent != null)
{
     var filtered = FilterBy(Items);
     var root_elements = filtered.Where(i => GetParent(i) == null).ToList();
     var non_root_elements = filtered.Where(i => GetParent(i) != null).ToList();
     <OrderedListByGetParent Parental="root_elements" Remaining="non_root_elements" GetParent="GetParent" />
}
```

I think if you try and use a value type (in my case I was using a ValueTuple) for the type parameter used by GetParent this will be a problem. Should there be a type constraint on the parameter to ensure it is a reference type?

Something like this?
`public partial class TreeViewBase<T> : ComponentBase where T : class`

**Comment by stefanloerwald** [comment]
Hi @Chadley08,

You're absolutely right that value types do not make sense in combination with `GetParent`. However, in combination with `GetChildren`, it works just fine. Restricting `TreeViewBase<T>` with `T : class` would break that use case.

I think the best we can do here is document this restriction. I will include an adapted doc comment on GetParent in the next release.

BR
Stefan
