### ISSUE TITLE
ListClass-attribute not working at TreeViewAsync

### ISSUE THREAD

**Issue by Kruki** [excubo-ag/Blazor.TreeViews#34]
Hi,
i was converting my TreeView to async loading and came across a little bug. I think the ListClass-attribute does not work on the TreeViewAsync-component.

Regards, Tobias

PS.: my team loves your TreeView-component!

**Comment by stefanloerwald** [comment]
Hi @Kruki,

Sorry for the delayed response. You are right, there is some code missing to enable this feature on async TreeViews! I've corrected that in commit f51b875 and this is going to be published as version 2.3.0 very soon.

BR
Stefan
