### ISSUE TITLE
Slow data loading , expand and collapse 

### ISSUE THREAD

**Issue by truecaller12** [excubo-ag/Blazor.TreeViews#36]
I am currently on .net 5 using this library for tree view. The loading takes a long time . Expanding and collapsing each node sometimes takes seconds ( 45 seconds) to come into action. Is this known ?

**Comment by stefanloerwald** [comment]
Hi @truecaller12,

That kind of low performance is certainly not normal. But without code, of course it's impossible to say why you might be experiencing this! Please take a look at the demo page (https://excubo-ag.github.io/Blazor.TreeViews). It has examples for many different use cases, and you can find the code to each page by following the link in the top right corner.

Hope that helps,
Stefan

**Comment by truecaller12** [comment]
```
 <div id="divTree">
            <TreeView Items="nodeCollections" GetChildren="(item) => item.Children">
                <ItemTemplate>
                    <Collapse @bind-Value="@context.Item.Collapsed" />
                    <ContextMenuTrigger MenuId="NodeMenu" Data="context.Item">
                        @*@onclick="() => { selectedNode = (selectedNode != context.Item) ? context.Item : null; }" border:@(selectedNode == context.Item ? "1px solid lightblue" : "0px"); padding:@(selectedNode == context.Item ? "5px" : "")*@
                        <div style="background-color: @(context.Item.BackColor);padding-left:0px;" @onclick:stopPropagation="true">
                            <i class="@context.Item.Image"></i>  @context.Item.Name <span> @(context.Item.Tag != null && context.Item.Tag.Prompt != null ? context.Item.Tag.Prompt : "")</span>
                        </div>
                    </ContextMenuTrigger>
                </ItemTemplate>
            </TreeView>
        </div>
```
this is the way i have defined the treeview..and nodecollections is a list .
version 2.3.3 tested on chrome

**Comment by stefanloerwald** [comment]
Sorry, I can't debug this for you just from looking at code. I'd advise you to investigate your performance issue by bisecting your code: Does this happen on a larger page or also when this code is the only thing on the page? Does this still happen when you replace the ItemTemplate by an empty one? What is re-rendered when you interact with which element?

**Comment by truecaller12** [comment]
performance is hit when i add the contextmenu..

**Comment by stefanloerwald** [comment]
Great! So have you tried adding the contextmenu code directly, instead of adding it from the library you're using?

It looks to me like an issue in that component, not here, but we can't be sure until you can produce a minimal example without external dependencies.

**Comment by truecaller12** [comment]
This ticket can be closed. The slowness is because of the ContextMenu lib.... without which the treeview performs flawless

**Comment by stefanloerwald** [comment]
Thanks for the feedback!
