### ISSUE TITLE
Memory usage when using treeview

### ISSUE THREAD

**Issue by AnDsoz** [excubo-ag/Blazor.TreeViews#37]
I am trying to load a treeview with 340000 nodes in total .This is extremely high i am aware but  the collapsed state too takes time and never loads.

Issues:
1.Out of memory exception when the nodes are around 35000
2.When i try to load the treeview in collapsed state it still takes a lot of time for the Ui to show.Why?
3.Is virtualizing the compoent possible?

**Comment by stefanloerwald** [comment]
Hi! 

There's currently no virtualization with this library. 

Have you tried TreeViewAsync? It might be worth considering, as it effectively allows lazy-loading.

If this is an important use case to you, please consider writing a PR for this feature.

Thanks
Stefan

**Comment by AnDsoz** [comment]
> Hi!
> 
> There's currently no virtualization with this library.
> 
> Have you tried TreeViewAsync? It might be worth considering, as it effectively allows lazy-loading.
> 
> If this is an important use case to you, please consider writing a PR for this feature.
> 
> Thanks Stefan

Any idea why with the collapsed state the treeview gives an out of memory exception? to show only  the first 7 parent nodes?

**Comment by stefanloerwald** [comment]
I haven't looked at the code in a while, but since there's no virtualization, I'm not surprised that there's trouble for such a large dataset.

**Comment by AnDsoz** [comment]
thank you for you reply.

Really wondering why when trying load in collapsed state should give an out of memory exception. i found it strange.
The collection is built very fast in the code behind and given to the component.
Just the computing and not displaying the nodes(collapsed state) with the loop in the component that takes over 3-5 mins or more until whenever the disconnect happens or exception is encountered for even 20000 nodes.
Note:In collapsed state only 7  nodes are to be shown.
