### ISSUE TITLE
bind-SelectedItems dosen´t work for custom objects

### ISSUE THREAD

**Issue by rockxl1** [excubo-ag/Blazor.TreeViews#38]
Hi guys, first love this treeview! Question:

I have an object called FolderDTO
```cs
public class FolderDTO{
public string Name;
public string Id;
public bool Collapsed=true;
public List<FolderDTO> SubFolders;
}
```

```html
 <TreeView @key="SelectedItems" Items="DataSource"  GetChildren="(item) => item.SubFolders" AllowSelection="true" @bind-SelectedItems="SelectedItems">
                <ItemTemplate>
                    <Collapse @bind-Value="@context.Item.Collapsed" />
                    <p class="FolderTree">@context.Item.Name</p>
                </ItemTemplate>
            </TreeView>

@code{
  [Paramenter]
   public List<FolderDTO> DataSource{ get; set; } 
  [Paramenter]
   public List<FolderDTO> SelectedItems{ get; set; } 
}
```

//other view just call
```html
<XFolder DataSource="MyList" SelectedItems="SelectedItems"/>
```

Works great! but if i had SelectedItems same values, the item not showing as Selected in UI. Do you know why? In exemples i just saw List<string> 

Thanks

**Comment by stefanloerwald** [comment]
Hi @rockxl1,

 this looks fine so far, sadly I don't understand what you mean by "but if I had SelectedItems same values". Could you explain say it in a different way? Or better yet, should code where it doesn't work?

Thanks
Stefan

**Comment by rockxl1** [comment]
Sorry about my english. If i set some default values in variable "SelectedItems", those values will not be selected in the tree. I think that is because is a complex list object not List of string, i am right?

**Comment by stefanloerwald** [comment]
Thanks for rephrasing. That should work, at least for the initial selection. It can only work if the SelectedItems are a subset of the actual instances you provide as Items.

Try `List<FolderDTO> SelectedItems => DataSource.Take(1).ToList();`, just to experiment. Does it show the initial selection like this?

**Comment by jasonracey** [comment]
@stefanloerwald Given the above, "can only work if the SelectedItems are a subset of the actual instances you provide as Items", how can the checkbox state be maintained if I were to leave the TreeView page and then return to it?

On the surface, it seems like it should be easy. The SelectedItems collection should just be stored in application memory and bound on page load. What I'm finding however, is that I can store SelectedItems in memory across pages no problem, but the checkbox state does not reflect the SelectedItems collection when I leave the TreeView page and return back to it.

In fact, if I check the first checkbox, leave the page, return to the page, then the collection contains the first item, but the first checkbox is no longer checked. Then I can check that box again, and now the collection contains 2 instances of the item corresponding to the first check box!

Here's the basic sequence in detail:

1. Load items into the tree
2. Bind selected items to a collection stored in application state.
3. Check a box.
4. Item is stored in the collection stored in application state.
5. Go to another page in the app.
6. Come back to the TreeView page.

Expected: collection contains the item checked in step 3 and corresponding checkbox is checked
Actual: collection contains the item checked in step 3 BUT corresponding checkbox is NOT checked

My code is here:  https://github.com/jasonracey/Keyworder/blob/01ebddaa52672ec1f905c9e25a00823a06ab4224/Keyworder/Pages/SelectKeywords.razor#L27C61-L27C61

**Comment by stefanloerwald** [comment]
Hi @jasonracey,

I cannot comment on your code as it would take me too much time to read it and understand how your saving state. The updated demo shows that state can be persisted and restored state works as expected.

Hope that helps,
Stefan
