### ISSUE TITLE
SelectedItems: Two or more immediate selected child items cause all current level items to be selected

### ISSUE THREAD

**Issue by yurafox** [excubo-ag/Blazor.TreeViews#41]
For some parent tree item, when programmatically set 2 or more immediate children items through SelectedItems property causes all items under this parent tree items become selected.

https://user-images.githubusercontent.com/15795957/205413799-1b081194-f667-4fe6-858b-8c2a98c03e8f.mp4

**Comment by stefanloerwald** [comment]
Hi @yurafox,

Thanks for the bug report and the video. Things are clearly going wrong there. Could you create a small example code snippet to reproduce this outside your larger application?

Thanks
Stefan

**Comment by yurafox** [comment]
Hi @stefanloerwald 

Unfortunately I have no time to prepare test project for you.
But I did fix the bug. Now it's working as expected.

So the fix is:

Line 80 in ListItem.razor.cs:
`var this_should_be_selected = Parent?.Selected == true || TreeView.SelectedItems?.Contains(Item) == true;`

should be

`var this_should_be_selected = Parent?.Selected == true && TreeView.SelectedItems?.Contains(Item) == true;`

Thanks,
Yurii
