### ISSUE TITLE
Broken styles on MAUI + Blazor?

### ISSUE THREAD

**Issue by AngeloTadeucci** [excubo-ag/Blazor.TreeViews#44]
Hello y'all. 

I've been trying to use TreeViews on MAUI, everything is working but I noticed the svg arrow is supposed to be hidden if the item doesn't have children.

The class names are there but there are no styles. Has anyone faced this behavior before?
![image](https://user-images.githubusercontent.com/15664821/216224097-d071f247-5c81-4332-8c85-c429346262ad.png)

**Comment by stefanloerwald** [comment]
Hi @AngeloTadeucci,

I've never experimented with Maui, so can't speak from experience, but I suspect that they didn't implement style tags within components.

You can test that hypothesis by creating a small component yourself, e.g.

```
<style> .foo { color: "red" } </style>
<p class="foo">Text</p>
```

If that's not showing red text in Maui, we've got it confirmed and I have a resolution in mind.

Stefan

**Comment by AngeloTadeucci** [comment]
Hey @stefanloerwald 

You are 100% correct, style tags don't work within components. 

What is the fix you have in mind? 
Thanks!

**Comment by stefanloerwald** [comment]
I'm thinking of https://github.com/excubo-ag/Blazor.TreeViews/commit/acf7da890141ec3e834b088a15db5f4f46123bf5

This commit should work for you, as long as the CSS isolation feature is supported in MAUI. Please let me know! The new version should be available any moment now.

**Comment by AngeloTadeucci** [comment]
It worked! Thank you.
