### ISSUE TITLE
SelectedItems: Setting the sub-items of a node (the first two) will cause all items at the current level to be selected.

### ISSUE THREAD

**Issue by sparkdeng0928** [excubo-ag/Blazor.TreeViews#46]
When the SelectedItems property is set programmatically to the first two sub-items (Ex: 3.1.1and3.1.2), all items under the parent tree item will be selected.

How to set up and solve this problem?

<button @onclick="@(() =>{ if (SelectedValues.Contains("3.1.1")) {return;} SelectedValues.Add("3.1.1");SelectedValues.Add("3.1.2");++version; InvokeAsync(StateHasChanged); })">
	Set 3.1.1 and 3.1.2 Selected
</button>

https://github.com/excubo-ag/Blazor.TreeViews/assets/158451967/3e254fa9-b1f9-4422-bded-524cca7389c2

**Comment by stefanloerwald** [comment]
Thanks for the bug report. Could you please provide the full code as well?

**Comment by sparkdeng0928** [comment]
Thank you for your reply, the full code is as follows

@using Excubo.Blazor.TreeViews


<TreeView @key="version" Items="Items" GetParent="GetParent" AllowSelection="true" @bind-SelectedItems="SelectedValues">
	<ItemTemplate>
		<div @onclick="() => { selectedItem = (selectedItem != context.Item) ? context.Item : null; }" style="background-color: @(selectedItem == context.Item ? "Highlight" : "inherit")">@context.Item</div>
	</ItemTemplate>
</TreeView>

<div>
	<button @onclick="@(() =>{ if (SelectedValues.Contains("3.1.1")) {return;} SelectedValues.Add("3.1.1");SelectedValues.Add("3.1.2");++version; InvokeAsync(StateHasChanged); })">
		Set 3.1.1 and 3.1.2 Selected
	</button>
</div>

@version

@code {

	protected override void OnInitialized()
	{
		base.OnInitialized();
	}
	private string selectedItem;
	// Modifications to the selection from beyond the TreeView (e.g. buttons below) require rerendering the treeview. 
	private int version;
	private List<string> SelectedValues = new List<string> { };

	private List<string> Items = new List<string>
	{
		"1",
		"1.1",
		"1.2",
		"2",
		"3",
		"3.1",
		"3.1.1",
		"3.1.2",
		"3.1.3",
		"3.1.4",
		"3.1.5"
	};
	private string GetParent(string item)
	{
		var last_period = item.LastIndexOf('.');
		if (last_period < 0)
		{
			return null; // no parent
		}
		else
		{
			return item.Substring(0, last_period);
		}
	}
}

**Comment by sparkdeng0928** [comment]
Thank you for your reply, the full code is as follows

[TreeView-Code.txt](https://github.com/excubo-ag/Blazor.TreeViews/files/14415802/TreeView-Code.txt)

**Comment by stefanloerwald** [comment]
Thank you. I understand the bug now.

Incrementing the version (which is, under the current implementation, necessary to update the selection programmatically), resets the parent child relationship of tree view nodes. As a consequence, at the time of processing node 3.1.1, no other children of 3.1 are evaluated so far, and thus the selection of 3.1.1 results in the full selection (not indeterminate) of 3.1 (and then also 3). Later, the other children of 3.1 are added, and then considered selected, because 3.1 is itself selected and not indeterminate at this point.

I think the only solution is to drop the version and implement another way of letting the component know that selection changed.

**Comment by sparkdeng0928** [comment]
Thank you for your explanation. 
I understand that program development is not an easy job. 
I am looking forward to the improved version.

**Comment by stefanloerwald** [comment]
I think I have a fix, but it will require more testing before I can submit it. This will also unfortunately require code changes on your end.
I hope to be able to send it out tomorrow, but I can't guarantee this.

**Comment by sparkdeng0928** [comment]
Thank you for your reply, looking forward to your new version being released

**Comment by stefanloerwald** [comment]
It's already released: https://www.nuget.org/packages/Excubo.Blazor.TreeViews/

**Comment by sparkdeng0928** [comment]
I have updated version 4.0.0, but the application problem is still not solved. Is there anything in the program code that I need to change?

![未命名](https://github.com/excubo-ag/Blazor.TreeViews/assets/158451967/451cd3fb-f4b7-4778-ae76-e01440e1422e)

**Comment by stefanloerwald** [comment]
Yes, see the changelog section in the readme
