### ISSUE TITLE
RefreshSelection question

### ISSUE THREAD

**Issue by murl** [excubo-ag/Blazor.TreeViews#47]
Hello I am currently using version 3.2.13 because my project cannot use .net 8.0 at this time. I noticed that in this version RefreshSelection for TreeView is not available. Is there a way in version 3.2.13 that I can update the selected item values? I have invoked StatHasChanged but selections did not update.

**Comment by stefanloerwald** [comment]
Hi @murl,

Older versions of .net are not in scope here, but are fully compatible with the code. For your case, I'd bridge the gap until you can migrate to net8.0 by creating a copy of this project, swapping out the target framework (and potentially dependencies), then referencing this modified version.

In general, I'd recommend migrating to the most recent LTS of .net. In most cases, this shouldn't involve more than changing the target framework.

Hope that helps,
Stefan
